# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Mat/Documents/workspace/doubleBarrel/doubleBarrel/monitor/gui/ui/mainUI.ui'
#
# Created: Fri Aug 17 17:46:09 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainUi(object):
    def setupUi(self, mainUi):
        mainUi.setObjectName(_fromUtf8("mainUi"))
        mainUi.resize(893, 432)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/compedShotgun.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainUi.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(mainUi)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.logSplitter = QtGui.QSplitter(self.centralwidget)
        self.logSplitter.setOrientation(QtCore.Qt.Vertical)
        self.logSplitter.setObjectName(_fromUtf8("logSplitter"))
        self.serverTree = QtGui.QTreeWidget(self.logSplitter)
        self.serverTree.setAlternatingRowColors(True)
        self.serverTree.setAnimated(True)
        self.serverTree.setObjectName(_fromUtf8("serverTree"))
        self.serverTree.header().setVisible(True)
        self.serverTree.header().setStretchLastSection(False)
        self.logDock = QtGui.QWidget(self.logSplitter)
        self.logDock.setObjectName(_fromUtf8("logDock"))
        self.verticalLayout = QtGui.QVBoxLayout(self.logDock)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.logOutput = QtGui.QTextBrowser(self.logDock)
        self.logOutput.setObjectName(_fromUtf8("logOutput"))
        self.verticalLayout.addWidget(self.logOutput)
        self.verticalLayout_3.addWidget(self.logSplitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.showLogLabel = QtGui.QLabel(self.centralwidget)
        self.showLogLabel.setText(_fromUtf8(""))
        self.showLogLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/monitor.png")))
        self.showLogLabel.setObjectName(_fromUtf8("showLogLabel"))
        self.verticalLayout_2.addWidget(self.showLogLabel)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.showLogCheck = QtGui.QCheckBox(self.centralwidget)
        self.showLogCheck.setObjectName(_fromUtf8("showLogCheck"))
        self.horizontalLayout.addWidget(self.showLogCheck)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addButton = QtGui.QPushButton(self.centralwidget)
        self.addButton.setMaximumSize(QtCore.QSize(32, 32))
        self.addButton.setToolTip(_fromUtf8(""))
        self.addButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon1)
        self.addButton.setIconSize(QtCore.QSize(32, 32))
        self.addButton.setFlat(True)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.horizontalLayout.addWidget(self.addButton)
        self.removeButton = QtGui.QPushButton(self.centralwidget)
        self.removeButton.setMaximumSize(QtCore.QSize(32, 32))
        self.removeButton.setToolTip(_fromUtf8(""))
        self.removeButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon2)
        self.removeButton.setIconSize(QtCore.QSize(32, 32))
        self.removeButton.setFlat(True)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.horizontalLayout.addWidget(self.removeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        mainUi.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuManage = QtGui.QMenu(self.menubar)
        self.menuManage.setObjectName(_fromUtf8("menuManage"))
        self.menuLog = QtGui.QMenu(self.menubar)
        self.menuLog.setObjectName(_fromUtf8("menuLog"))
        self.menuPreferences = QtGui.QMenu(self.menubar)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        mainUi.setMenuBar(self.menubar)
        self.verticalSplitAction = QtGui.QAction(mainUi)
        self.verticalSplitAction.setCheckable(True)
        self.verticalSplitAction.setChecked(True)
        self.verticalSplitAction.setObjectName(_fromUtf8("verticalSplitAction"))
        self.horizontalSplitAction = QtGui.QAction(mainUi)
        self.horizontalSplitAction.setCheckable(True)
        self.horizontalSplitAction.setObjectName(_fromUtf8("horizontalSplitAction"))
        self.showLogAction = QtGui.QAction(mainUi)
        self.showLogAction.setCheckable(True)
        self.showLogAction.setObjectName(_fromUtf8("showLogAction"))
        self.addServerAction = QtGui.QAction(mainUi)
        self.addServerAction.setIcon(icon1)
        self.addServerAction.setObjectName(_fromUtf8("addServerAction"))
        self.removeServerAction = QtGui.QAction(mainUi)
        self.removeServerAction.setIcon(icon2)
        self.removeServerAction.setObjectName(_fromUtf8("removeServerAction"))
        self.hideLogAction = QtGui.QAction(mainUi)
        self.hideLogAction.setCheckable(True)
        self.hideLogAction.setChecked(True)
        self.hideLogAction.setObjectName(_fromUtf8("hideLogAction"))
        self.actionUnlock = QtGui.QAction(mainUi)
        self.actionUnlock.setObjectName(_fromUtf8("actionUnlock"))
        self.restartServerAction = QtGui.QAction(mainUi)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartServerAction.setIcon(icon3)
        self.restartServerAction.setObjectName(_fromUtf8("restartServerAction"))
        self.simpleModeAction = QtGui.QAction(mainUi)
        self.simpleModeAction.setCheckable(True)
        self.simpleModeAction.setChecked(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/star.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simpleModeAction.setIcon(icon4)
        self.simpleModeAction.setObjectName(_fromUtf8("simpleModeAction"))
        self.advancedModeAction = QtGui.QAction(mainUi)
        self.advancedModeAction.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/advanced.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advancedModeAction.setIcon(icon5)
        self.advancedModeAction.setObjectName(_fromUtf8("advancedModeAction"))
        self.setServerFileAction = QtGui.QAction(mainUi)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/server.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setServerFileAction.setIcon(icon6)
        self.setServerFileAction.setObjectName(_fromUtf8("setServerFileAction"))
        self.startServerAction = QtGui.QAction(mainUi)
        self.startServerAction.setObjectName(_fromUtf8("startServerAction"))
        self.stopServerAction = QtGui.QAction(mainUi)
        self.stopServerAction.setObjectName(_fromUtf8("stopServerAction"))
        self.menuManage.addAction(self.addServerAction)
        self.menuManage.addAction(self.removeServerAction)
        self.menuManage.addSeparator()
        self.menuManage.addAction(self.restartServerAction)
        self.menuManage.addSeparator()
        self.menuManage.addAction(self.startServerAction)
        self.menuManage.addAction(self.stopServerAction)
        self.menuLog.addAction(self.showLogAction)
        self.menuLog.addAction(self.hideLogAction)
        self.menuLog.addSeparator()
        self.menuLog.addAction(self.verticalSplitAction)
        self.menuLog.addAction(self.horizontalSplitAction)
        self.menuPreferences.addAction(self.simpleModeAction)
        self.menuPreferences.addAction(self.advancedModeAction)
        self.menubar.addAction(self.menuManage.menuAction())
        self.menubar.addAction(self.menuLog.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())

        self.retranslateUi(mainUi)
        QtCore.QMetaObject.connectSlotsByName(mainUi)

    def retranslateUi(self, mainUi):
        mainUi.setWindowTitle(QtGui.QApplication.translate("mainUi", "Double Barrel Server Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.serverTree.setSortingEnabled(True)
        self.serverTree.headerItem().setText(0, QtGui.QApplication.translate("mainUi", "Script Name", None, QtGui.QApplication.UnicodeUTF8))
        self.serverTree.headerItem().setText(1, QtGui.QApplication.translate("mainUi", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.showLogCheck.setText(QtGui.QApplication.translate("mainUi", "Show log", None, QtGui.QApplication.UnicodeUTF8))
        self.menuManage.setTitle(QtGui.QApplication.translate("mainUi", "Manage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLog.setTitle(QtGui.QApplication.translate("mainUi", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPreferences.setTitle(QtGui.QApplication.translate("mainUi", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalSplitAction.setText(QtGui.QApplication.translate("mainUi", "Vertical Split", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalSplitAction.setText(QtGui.QApplication.translate("mainUi", "Horizontal Split", None, QtGui.QApplication.UnicodeUTF8))
        self.showLogAction.setText(QtGui.QApplication.translate("mainUi", "Show Log", None, QtGui.QApplication.UnicodeUTF8))
        self.addServerAction.setText(QtGui.QApplication.translate("mainUi", "Add Server", None, QtGui.QApplication.UnicodeUTF8))
        self.removeServerAction.setText(QtGui.QApplication.translate("mainUi", "Remove Server", None, QtGui.QApplication.UnicodeUTF8))
        self.hideLogAction.setText(QtGui.QApplication.translate("mainUi", "Hide Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnlock.setText(QtGui.QApplication.translate("mainUi", "Unlock", None, QtGui.QApplication.UnicodeUTF8))
        self.restartServerAction.setText(QtGui.QApplication.translate("mainUi", "Restart Server", None, QtGui.QApplication.UnicodeUTF8))
        self.simpleModeAction.setText(QtGui.QApplication.translate("mainUi", "Simple", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedModeAction.setText(QtGui.QApplication.translate("mainUi", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.setServerFileAction.setText(QtGui.QApplication.translate("mainUi", "Set Server File", None, QtGui.QApplication.UnicodeUTF8))
        self.startServerAction.setText(QtGui.QApplication.translate("mainUi", "Start Server", None, QtGui.QApplication.UnicodeUTF8))
        self.stopServerAction.setText(QtGui.QApplication.translate("mainUi", "Stop Server", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
